## Other functions for working with APT ##

##' Plot the trajectories of a temperature ladder of an adaptive parallel tempering algorithm
##'
##' Returns two plots, one with T~iterations, the other log10(T)~iterations.
##' @title plot.tempTraj
##' @param cAPT - an APT object generated by buildAPT and compiled by compileNimble.
##' @return A plot of the trajectories.
##' @author David Pleydell
##' @seealso An example is provided in the documentation of buildAPT.
##' @import nimble
##' @importFrom grDevices rainbow n2mfrow
##' @importFrom graphics lines par plot
##' @export
plotTempTraj <- function(cAPT) {
    traj <- cAPT$tempTraj
    nRow <- nrow(traj)
    nCol <- ncol(traj)
    myCols <- rainbow(nCol)
    par(mfrow=n2mfrow(2))
    YLIM <- range(pretty(c(0, cAPT$tempTraj[,nCol])))
    plot(1:nRow, cAPT$tempTraj[,nCol], typ="n", ylim=YLIM, xlab="Iteration", ylab="Temperature")
    for (ii in 1:nCol)
        lines(cAPT$tempTraj[,ii], col=myCols[ii])
    YLIM <- range(pretty(c(0, log10(cAPT$tempTraj[,nCol]))))
    plot(1:nRow, log10(cAPT$tempTraj[,nCol]), typ="n", ylim=YLIM, xlab="Iteration", ylab="log10(Temperature)")
    for (ii in 1:nCol)
        lines(log10(cAPT$tempTraj[,ii]), col=myCols[ii])
}
