## Other functions for working with APT ##

##' Plot the trajectories of a temperature ladder of an adaptive parallel tempering algorithm
##'
##' Returns two plots, one with T~iterations, the other log10(T)~iterations.
##' @title plot.tempTraj
##' @param apt - an APT object generated by buildAPT
##' @return a plot.
##' @author David Pleydell
##' @export
plot.tempTraj <- function(apt) {
    traj <- apt$tempTraj
    nRow <- nrow(traj)
    nCol <- ncol(traj)
    myCols <- rainbow(nCol)
    par(mfrow=n2mfrow(2))
    YLIM <- range(pretty(c(0, apt$tempTraj[,nCol])))
    plot(1:nRow, apt$tempTraj[,nCol], typ="n", ylim=YLIM, xlab="Iteration", ylab="Temperature")
    for (ii in 1:nCol)
        lines(apt$tempTraj[,ii], col=myCols[ii])
    YLIM <- range(pretty(c(0, log10(apt$tempTraj[,nCol]))))
    plot(1:nRow, log10(apt$tempTraj[,nCol]), typ="n", ylim=YLIM, xlab="Iteration", ylab="log10(Temperature)")
    for (ii in 1:nCol)
        lines(log10(apt$tempTraj[,ii]), col=myCols[ii])
}
